#lang racket
(require "frame.rkt")
(require "segment.rkt")
(require "draw.rkt")
(require "vector.rkt")
(require "transform_painter.rkt")

(define (segment->painter segment-list)
    (lambda (frame)
        (for-each (lambda (segment)
                        (drawline ((frame-coord-map frame) (start-segment segment))
                                   ((frame-coord-map frame) (end-segment segment))
                                  ))
                  segment-list)))

;:
;: exercise 2.49
;: a) The painter that draws the outline of the designated frame.
(define frame-edge-painter
    (segment->painter (list (make-segment (make-vect 0 0)
                                          (make-vect 0 1))
                            (make-segment (make-vect 0 0)
                                          (make-vect 1 0))
                            (make-segment (make-vect 0 1)
                                          (make-vect 1 1))
                            (make-segment (make-vect 1 0)
                                          (make-vect 1 1)))))
;: b) The painter that draws an "X" by connecting opposite
;:    corners of the frame.
(define frame-x-painter
    (segment->painter (list (make-segment (make-vect 0 0)
                                          (make-vect 1 1))
                            (make-segment (make-vect 1 0)
                                          (make-vect 0 1)))))

;: c) The painter that draws a diamond shape by connnecting
;:    the midpoint of the sides of the frame.
(define frame-diamond-painter
    (segment->painter (list (make-segment (make-vect 0 0.5)
                                          (make-vect 0.5 0))
                            (make-segment (make-vect 0.5 0)
                                          (make-vect 1 0.5))
                            (make-segment (make-vect 1 0.5)
                                          (make-vect 0.5 1))
                            (make-segment (make-vect 0.5 1)
                                          (make-vect 0 0.5)))))

(define wave
  (segment->painter (list (make-segment (make-vect 0.1 0)
                                        (make-vect 0.3 0.1))
                          (make-segment (make-vect 0.3 0)
                                        (make-vect 0.5 0.1))
                          (make-segment (make-vect 0.3 0.1)
                                        (make-vect 0.25 0.3))
                          (make-segment (make-vect 0.5 0.1)
                                        (make-vect 0.3 0.3))
                          (make-segment (make-vect 0.25 0.3)
                                        (make-vect 0.25 0.4))
                          (make-segment (make-vect 0.25 0.4)
                                        (make-vect 0.1 0.35))
                          (make-segment (make-vect 0.1 0.35)
                                        (make-vect 0 0.4))
                          (make-segment (make-vect 0 0.6)
                                        (make-vect 0.1 0.65))
                          (make-segment (make-vect 0.1 0.65)
                                        (make-vect 0.25 0.6))
                          (make-segment (make-vect 0.25 0.6)
                                        (make-vect 0.25 0.75))
                          (make-segment (make-vect 0.25 0.75)
                                        (make-vect 0.65 1))
                          (make-segment (make-vect 0.3 0.3)
                                        (make-vect 0.4 0.35))
                          (make-segment (make-vect 0.4 0.35)
                                        (make-vect 1 0.25))
                          (make-segment (make-vect 0.6 0.5)
                                        (make-vect 1 0.4))
                          (make-segment (make-vect 0.6 0.5)
                                        (make-vect 1 0.6))
                          (make-segment (make-vect 0.5 0.65)
                                        (make-vect 1 0.8))
                          (make-segment (make-vect 0.5 0.65)
                                        (make-vect 0.85 1))
                          )))

;: Test
(define frame-no (make-frame (make-vect 0 0)
                             (make-vect 1 0)
                             (make-vect 0 1)))
(define frame-scale (make-frame (make-vect 0 0)
                             (make-vect 1 0)
                             (make-vect 0 0.6)))
(define frame-half (make-frame (make-vect 0 0)                          
                           (make-vect 0.5 0)
                           (make-vect 0 0.5)))
(define frame-rotate90 (make-frame (make-vect 0 0.5)
                                 
                                 (make-vect 0.5 0.5)
                                 (make-vect 0.5 -0.5)))
;(frame-edge-painter frame-no)
;(frame-x-painter frame-half)
;(frame-diamond-painter frame1)
;(wave frame-no)
;(wave frame-half)
;(wave frame-rotate90)
;(wave frame-scale)
;((squash-inwards wave) frame-no)
((below wave wave) frame-no)
;(close-draw)