;: exercise 4.44


(define (safe? k p)
    (define (iter new rest c)
        (cond ((null? rest) true)
              ((= c k) true)
              ((or (= (car rest) new) 
                   (= (car rest) (- new c)) 
                   (= (car rest) (+ new c))) false)
              (else (iter new (cdr rest) (+ c 1)))))
    (iter (car p) (cdr p) 1))

(define (eight-queens)
    (define (queen-cols k)
        (if (= k 0)
            '()
            (let ((q (amb 1 2 3 4 5 6 7 8))
                  (kqs (queen-cols (- k 1))))
                (require (safe? k (cons q kqs)))
                (cons q kqs))))
    (queen-cols 8))

(define (attack? x y step)
    (or (= x y)
        (= (abs (- x y)) step)))
(define (eight-queens)
    (let (
         (q1 (amb 1 2 3 4 5 6 7 8))
         (q2 (amb 1 2 3 4 5 6 7 8))
         (q3 (amb 1 2 3 4 5 6 7 8))
         (q4 (amb 1 2 3 4 5 6 7 8))
         (q5 (amb 1 2 3 4 5 6 7 8))
         (q6 (amb 1 2 3 4 5 6 7 8))
         (q7 (amb 1 2 3 4 5 6 7 8))
         (q8 (amb 1 2 3 4 5 6 7 8))
        )
        (require (not (attack? q1 q2 1)))
        (require (not (attack? q1 q3 2)))
        (require (not (attack? q1 q4 3)))
        (require (not (attack? q1 q5 4)))
        (require (not (attack? q1 q6 5)))
        (require (not (attack? q1 q7 6)))
        (require (not (attack? q1 q8 7)))
        (require (not (attack? q2 q3 1)))
        (require (not (attack? q2 q4 2)))
        (require (not (attack? q2 q5 3)))
        (require (not (attack? q2 q6 4)))
        (require (not (attack? q2 q7 5)))
        (require (not (attack? q2 q8 6)))
        (require (not (attack? q3 q4 1)))
        (require (not (attack? q3 q5 2)))
        (require (not (attack? q3 q6 3)))
        (require (not (attack? q3 q7 4)))
        (require (not (attack? q3 q8 5)))
        (require (not (attack? q4 q5 1)))
        (require (not (attack? q4 q6 2)))
        (require (not (attack? q4 q7 3)))
        (require (not (attack? q4 q8 4)))
        (require (not (attack? q5 q6 1)))
        (require (not (attack? q5 q7 2)))
        (require (not (attack? q5 q8 3)))
        (require (not (attack? q6 q7 1)))
        (require (not (attack? q6 q8 2)))
        (require (not (attack? q7 q8 1)))
        (list q1 q2 q3 q4 q5 q6 q7 q8)))
